name: main
on: [push]
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:

      - run: sudo apt-get install pandoc # enhancement: pin down the version (conda ?)

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install -g decktape   

      - uses: actions/checkout@v2
      - run: ./build #--pdf
      - run: ls

#      - run: git add -f *.html # does it help the deploy ?
#      - run: git config user.email "Sebastien.Boisgerault@gmail.com"
#      - run: git config user.name "Sébastien.Boisgérault"
#      - run: git commit -am "add html files"


#      - name: deploy to gh-pages
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: "."
#          force_orphan: true

# Killed gh-pages on github

      - run: echo "*.tttt" > .gitignore
      - run: echo "*.tttt" > .gitignore.bak
      - name: deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "."
          SINGLE_COMMIT: true
