name: main
on: [push]
jobs:
  main:
    runs-on: ubuntu-20.04
    steps:

      - run: sudo apt-get install pandoc # fix: pin down the version (conda ?)

      - uses: actions/checkout@v2
      - run: ./build
      - run: ls

      - name: deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: "."
          SINGLE_COMMIT: true
